### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by rcon420** [outsparkled/pterodactyl-power-action#1]
Hi! Your script works I managed to push the power action restart server but how I can pull updated files from github repo to my csgo server on this panel?

**Comment by outsparkled** [comment]
Automatically pulling is done by adding a `git pull;` to your startup command. (Of course this requires that you have your repository set as the remote origin.)

I recommend contacting the maintainer of the Pterodactyl egg you are using for more information.

**Comment by rcon420** [comment]
> Automatically pulling is done by adding a `git pull;` to your startup command. (Of course this requires that you have your repository set as the remote origin.)
> 
> I recommend contacting the maintainer of the Pterodactyl egg you are using for more information.

from my panel, I see that they use this docker image ghcr.io/pterodactyl/games:source. If you have time I'm willing to pay you if u can help set it up I'm not too familiar with such stuff.

**Comment by outsparkled** [comment]
Sorry for the late response. I'm sorry, but I'm currently not able to assist you. If your server is managed, you may be able to receive help from your hosting service provider.
